model: claude-3-7-sonnet-20250219
cache-prompts: true
cache-keepalive-pings: 2
stream: false
auto-commits: true
watch-files: true
read:
  - Python.md
  - README.md
  - pyproject.toml
  - llms-ctx.txt
  - toolsepc-ctx.md
