[project]
name = "prudentia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyright>=1.1.396",
    "python-fasthtml>=0.12.4",
    "ruff>=0.9.10",
]
